name: 'Caching for Turborepo'
description:
  'Sets up Turborepo Remote Caching to work with GitHub Actions built-in cache.
  No Vercel account access tokens needed.'
author: 'HUORT Louis'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'upload-cloud'
  color: 'blue'

# Define your inputs here.
inputs:
  provider:
    description: 'Provider to use for caching (github, s3)'
    required: true
    default: 'github'
  cache-prefix:
    description: 'Prefix for the cache key'
    required: false
    default: turbogha_
  max-age:
    description:
      'Cleanup cache files older than this age (ex: 1mo, 1w, 1d). using
      https://www.npmjs.com/package/parse-duration'
    required: false
  max-files:
    description:
      'Cleanup oldest cache files when number of files exceeds this limit (ex:
      300)'
    required: false
  max-size:
    description:
      'Cleanup oldest cache files when total size exceeds this limit (ex: 100mb,
      10gb)'
    required: false
  s3-access-key-id:
    description: 'AWS S3 access key ID (required when provider is s3)'
    required: false
  s3-secret-access-key:
    description: 'AWS S3 secret access key (required when provider is s3)'
    required: false
  s3-bucket:
    description: 'AWS S3 bucket name (required when provider is s3)'
    required: false
  s3-region:
    description: 'AWS S3 region (required when provider is s3)'
    required: false
  s3-prefix:
    description: 'Prefix for S3 objects'
    required: false
    default: 'turbogha/'

runs:
  using: node20
  main: dist/setup/index.js
  post: dist/post/index.js
