name: 'Caching for Turborepo'
description:
  'Sets up Turborepo Remote Caching to work with GitHub Actions built-in cache.
  No Vercel account access tokens needed.'
author: 'HUORT Louis'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'upload-cloud'
  color: 'blue'

# Define your inputs here.
inputs:
  cache-prefix:
    description: 'Prefix for the cache key'
    required: false
    default: turbogha_

runs:
  using: node20
  main: 'dist/index.js'
  post: 'dist/index.js --post-setup'
